### ISSUE TITLE
Fatal error when mapper expects array of objects but json field is object

### ISSUE THREAD

**Issue by Stefaminator** [JsonMapper/JsonMapper#154]
Fatal error when mapper expects array of objects but json field is object

**To Reproduce**
1. Expect array of objects in your php docs section for some field of your outer object
2. Pass json with a plain object instead 
3. try to mapObject

**Expected behavior**
json field should be ignored because of type mismatch

**Stacktrace**
 PHP Fatal error:  Uncaught TypeError: JsonMapper\\JsonMapper::mapObject(): Argument #1 ($json) must be of type stdClass, array given, called in /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php on line 389 and defined in /vendor/json-mapper/json-mapper/src/JsonMapper.php:107
Stack trace:
#0 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(389): JsonMapper\\JsonMapper->mapObject()
#1 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(367): JsonMapper\\Handler\\PropertyMapper->mapToSingleObject()
#2 [internal function]: JsonMapper\\Handler\\PropertyMapper->JsonMapper\\Handler\\{closure}()
#3 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(368): array_map()
#4 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(420): JsonMapper\\Handler\\PropertyMapper->mapToArrayOfObjects()
#5 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(211): JsonMapper\\Handler\\PropertyMapper->mapToObjects()
#6 /vendor/json-mapper/json-mapper/src/Handler/PropertyMapper.php(82): JsonMapper\\Handler\\PropertyMapper->mapPropertyValue()
#7 /vendor/json-mapper/json-mapper/src/Middleware/AbstractMiddleware.php(25): JsonMapper\\Handler\\PropertyMapper->__invoke()
#8 /vendor/json-mapper/json-mapper/src/Middleware/AbstractMiddleware.php(25): JsonMapper\\Middleware\\AbstractMiddleware->JsonMapper\\Middleware\\{closure}()
#9 /vendor/json-mapper/json-mapper/src/JsonMapper.php(116): JsonMapper\\Middleware\\AbstractMiddleware->JsonMapper\\Middleware\\{closure}()
#10 /[..]/myfile.php(91): JsonMapper\\JsonMapper->mapObject()

**Environment (please complete the following information):**
 - PHP: 8.1

**Comment by Stefaminator** [comment]
I created a little test to reproduce the fatal error. I recognized that I am able to catch the "TypeError" by using a try-catch block. So I am not really sure if this is the expected behaviour (throwing a "TypeError") or a bug. 

```
use JsonMapper\JsonMapperFactory;

class Test {

    /**
     * @var Test[]
     */
    public array $array_of_test = [];

    /**
     * @var string
     */
    public string $str = "";
}

$test_cases = [];
$test_cases[] = '{"array_of_test":[{"str":"yes"}], "str":"i do"}';
$test_cases[] = '{"array_of_test":{"str":"yes"}, "str":"i do"}';
$test_cases[] = '{"array_of_test":"yes", "str":"i do"}';

foreach($test_cases as $json) {

    try {
        $std_class = json_decode($json, false, 512, JSON_THROW_ON_ERROR);

        $mapper = (new JsonMapperFactory())->default();

        $test = $mapper->mapObject($std_class, new Test());

        var_dump($test);
    } catch (TypeError $e) {
        var_dump($e);
    }

}
```

**Comment by DannyvdSluijs** [comment]
Thanks for your extensive report. This really helpful in making JsonMapper better. 

I’ll try to look into resolving this as soon as possible. One question though, if you get a single object instead of an array wouldn’t you say your model is incorrect? And the php doc needs some tweaking or did I mis-interpret something in your report?

**Comment by Stefaminator** [comment]
In my opinion, the JsonMapper did everything right. It received incorrect/incompatible json and so it didn't proceed the mapping. Only case 1 of the upper test was correct json, case 2 and 3 are incorrect in relation to the php doc block. So it shouldn't be mapped.  But: I was confusing about the thrown Error. It was a native "TypeError". So the programm will crash if you not explicit catching it. I did not expect that and I do not know if this is documented somewhere. I expected a maximum of one exception, not a "FatalError". Maybe this fact should be adjusted. But that's just a suggestion. 

Additionally it would be great to receive information about which node of the given Object was responsible for the type mismatch exception.
